package com.heihei.bookrecommendsystem.mahout;

public enum SimilarityEnum {
    PEARSON,EUCLIDEAN,COSINE,TANIMOTO,LOGLIKELIHOOD,SPEARMAN,CITYBLOCK,FARTHEST_NEIGHBOR_CLUSTER, NEAREST_NEIGHBOR_CLUSTER
}
